# Generated by Django 4.0.2 on 2024-11-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='showtime',
            new_name='show_time',
        ),
    ]
