# Generated by Django 4.0.2 on 2024-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_showtime_moviesession_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies_of_a_genre', to='db.Genre'),
        ),
    ]
